/**
 * nine-install
 * @app-description Installs nine toolkit to /lib/ for global access
 */

import { UI } from "./lib/ui";

const ui = UI.ctx();
const LIB_DIR = "/lib";

// Color configuration - uses UI palette keys
const COLORS = {
  usageExample: "cyan",
} as const;

async function main() {
  const args = Shell.GetArgs();
  const isUninstall = args.includes("--uninstall") || args.includes("-u");

  ui.printBlockTitle("NINE INSTALLER");
  ui.newLine();

  if (isUninstall) {
    await uninstall();
  } else {
    await install();
  }
}

interface DirEntry {
  name: string;
  isFolder: boolean;
  extension?: string;
}

async function install() {
  // Get current directory (repo location)
  const cwd = await FileSystem.cwd();
  const repoPath = cwd.absolutePath;

  // Check if we're in a valid nine repo
  try {
    const files = await FileSystem.ReadDir(".") as DirEntry[];
    const hasNine = files.some((f) => f.name === "nine" && !f.isFolder);
    const hasLib = files.some((f) => f.name === "lib" && f.isFolder);

    if (!hasNine || !hasLib) {
      ui.error("Not a valid nine repository");
      ui.info("nine.ts or lib/ folder not found");
      return;
    }
  } catch (e) {
    ui.error("Cannot read current directory");
    return;
  }

  // Check if already installed
  const wrapperPath = `${LIB_DIR}/nine.ts`;
  const alreadyInstalled = await fileExists(wrapperPath);

  if (alreadyInstalled) {
    ui.warn("nine is already installed!");
    const shouldOverwrite = await ui.confirm("Overwrite");
    if (!shouldOverwrite) {
      ui.info("Installation cancelled");
      return;
    }
    ui.info("Updating wrapper...");
  }

  ui.info(`Repository: ${repoPath}`);
  ui.newLine();

  // Create wrapper in /lib/
  ui.info("Creating wrapper in /lib/...");

  // Import path needs .. to go from /lib/ up to root, then to repo
  const importPath = `..${repoPath}/nine`;

  const wrapperContent = `/**
 * nine - Wrapper for global access
 * Auto-generated by install.ts
 * Points to: ${repoPath}
 */
import { main } from "${importPath}";
await main(Shell.GetArgs(), "${repoPath}");
`;

  await FileSystem.WriteFile(wrapperPath, wrapperContent, { absolute: true });

  ui.success("Wrapper created");
  ui.newLine();

  // Success
  ui.success("nine installed successfully!");
  ui.newLine();
  ui.section("USAGE");
  ui.print("  nine <ip>          Scan target IP", COLORS.usageExample);
  ui.print("  nine -h            Show help", COLORS.usageExample);
  ui.newLine();
  ui.info(`Repository: ${repoPath}`);
  ui.info(`Data: ./loot/ (relative to repo)`);
}

async function uninstall() {
  ui.info("Uninstalling nine...");

  const wrapperPath = `${LIB_DIR}/nine.ts`;
  const exists = await fileExists(wrapperPath);

  if (exists) {
    await FileSystem.Remove(wrapperPath, { absolute: true });
    ui.success("Removed /lib/nine.ts");
  } else {
    ui.warn("nine not found in /lib/");
  }

  ui.newLine();
  ui.success("nine uninstalled");
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await FileSystem.ReadFile(path, { absolute: true });
    return true;
  } catch {
    return false;
  }
}

main();
